name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Code checkout 
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Docker build image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: |
        echo "Initialize build"
        docker build -t $DOCKER_USER/docker-graphql:0.0.2 .
        docker build -t $DOCKER_USER/docker-graphql:latest .

    - name: Docker push image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: |
        echo "Initialize push"
        docker push $DOCKER_USER/docker-graphql:0.0.2
        docker push $DOCKER_USER/docker-graphql:latest
      
      
        
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
